name: OMERO User Help Website
plugins:
  - jekyll-redirect-from
markdown: redcarpet
highlighter: rouge

url: https://snoopycrimecrop.github.io
repository: ome/ome-help
baseurl: /ome-help
clsbaseurl: /ome-help/cls
